const { GoogleGenAI } = require("@google/genai");

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
});

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
    const prompt = `Generate a detailed interview preparation report based on these candidate metrics:
    Resume Context: ${resume || "None provided"}
    Self Description: ${selfDescription}
    Target Job Description: ${jobDescription}`;

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: {
                type: "OBJECT",
                properties: {
                    matchScore: { 
                        type: "INTEGER", 
                        description: "A score between 0 to 100 indicating how well the candidate matches the job description." 
                    },
                    title: { 
                        type: "STRING", 
                        description: "The targeted job title or role designation." 
                    },
                    technicalQuestions: {
                        type: "ARRAY",
                        description: "5-7 technical interview questions relevant to the profile.",
                        items: {
                            type: "OBJECT",
                            properties: {
                                question: { type: "STRING" },
                                intention: { type: "STRING" },
                                answer: { type: "STRING" }
                            },
                            required: ["question", "intention", "answer"]
                        }
                    },
                    behavioralQuestions: {
                        type: "ARRAY",
                        description: "4-5 behavioral interview questions.",
                        items: {
                            type: "OBJECT",
                            properties: {
                                question: { type: "STRING" },
                                intention: { type: "STRING" },
                                answer: { type: "STRING" }
                            },
                            required: ["question", "intention", "answer"]
                        }
                    },
                    skillGaps: {
                        type: "ARRAY",
                        description: "Identified gaps compared to requirements.",
                        items: {
                            type: "OBJECT",
                            properties: {
                                skill: { type: "STRING" },
                                severity: { type: "STRING", enum: ["low", "medium", "high"] }
                            },
                            required: ["skill", "severity"]
                        }
                    },
                    preparationPlan: {
                        type: "ARRAY",
                        description: "A structured day-by-day preparation roadmap.",
                        items: {
                            type: "OBJECT",
                            properties: {
                                day: { type: "INTEGER" },
                                focus: { type: "STRING" },
                                tasks: { 
                                    type: "ARRAY", 
                                    items: { type: "STRING" } 
                                }
                            },
                            required: ["day", "focus", "tasks"]
                        }
                    }
                },
                required: ["matchScore", "title", "technicalQuestions", "behavioralQuestions", "skillGaps", "preparationPlan"]
            }
        }
    });

    return JSON.parse(response.text);
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema),
        }
    })
      const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer

}


module.exports = {generateInterviewReport,generateResumePdf};